In [7]:
from __future__ import division, print_function, unicode_literals
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10,6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

In [2]:
np.ones((10, 5)).shape

(10, 5)

In [3]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [8]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
print(np.issubdtype(ints.dtype, np.integer))
print(np.issubdtype(floats.dtype, np.floating))

True
True


In [9]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [11]:
np.uint32.mro()

[numpy.uint32,
 numpy.unsignedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [12]:
np.issubdtype(ints.dtype, np.number)

True

In [14]:
arr = np.arange(8)
print(arr)
arr.reshape((4,2))

[0 1 2 3 4 5 6 7]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [15]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
arr = np.arange(15)
arr.reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
other_arr = np.ones((3, 5))
print(other_arr.shape)
arr.reshape(other_arr.shape)

(3, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
arr = np.arange(15).reshape((5, 3))
print(arr)
arr.ravel()

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr = np.arange(12).reshape((3, 4))
print(arr)
print(arr.ravel())
print(arr.ravel('F'))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [22]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.concatenate([arr1, arr2], axis=0))
print(np.concatenate([arr1, arr2], axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [23]:
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [25]:
arr = np.random.randn(5, 2)
print(arr)
first, second, third = np.split(arr, [1, 3])
print(first)
print(second)
print(third)

[[ 1.0072 -1.2962]
 [ 0.275   0.2289]
 [ 1.3529  0.8864]
 [-2.0016 -0.3718]
 [ 1.669  -0.4386]]
[[ 1.0072 -1.2962]]
[[0.275  0.2289]
 [1.3529 0.8864]]
[[-2.0016 -0.3718]
 [ 1.669  -0.4386]]


In [27]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
print(np.r_[arr1, arr2])
print(np.c_[np.r_[arr1, arr2], arr])

[[ 0.      1.    ]
 [ 2.      3.    ]
 [ 4.      5.    ]
 [ 0.3026  0.5238]
 [ 0.0009  1.3438]
 [-0.7135 -0.8312]]
[[ 0.      1.      0.    ]
 [ 2.      3.      1.    ]
 [ 4.      5.      2.    ]
 [ 0.3026  0.5238  3.    ]
 [ 0.0009  1.3438  4.    ]
 [-0.7135 -0.8312  5.    ]]


In [28]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [29]:
arr = np.arange(3)
print(arr)
arr.repeat(3)

[0 1 2]


array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [30]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [31]:
arr = np.random.randn(2, 2)
print(arr)
arr.repeat(2, axis=0)

[[-2.3702 -1.8608]
 [-0.8608  0.5601]]


array([[-2.3702, -1.8608],
       [-2.3702, -1.8608],
       [-0.8608,  0.5601],
       [-0.8608,  0.5601]])

In [32]:
print(arr.repeat([2, 3], axis=0))
print(arr.repeat([2, 3], axis=1))

[[-2.3702 -1.8608]
 [-2.3702 -1.8608]
 [-0.8608  0.5601]
 [-0.8608  0.5601]
 [-0.8608  0.5601]]
[[-2.3702 -2.3702 -1.8608 -1.8608 -1.8608]
 [-0.8608 -0.8608  0.5601  0.5601  0.5601]]


In [33]:
print(arr)
np.tile(arr, 2)

[[-2.3702 -1.8608]
 [-0.8608  0.5601]]


array([[-2.3702, -1.8608, -2.3702, -1.8608],
       [-0.8608,  0.5601, -0.8608,  0.5601]])

In [34]:
print(arr)
print(np.tile(arr, (2, 1)))
print(np.tile(arr, (3, 2)))

[[-2.3702 -1.8608]
 [-0.8608  0.5601]]
[[-2.3702 -1.8608]
 [-0.8608  0.5601]
 [-2.3702 -1.8608]
 [-0.8608  0.5601]]
[[-2.3702 -1.8608 -2.3702 -1.8608]
 [-0.8608  0.5601 -0.8608  0.5601]
 [-2.3702 -1.8608 -2.3702 -1.8608]
 [-0.8608  0.5601 -0.8608  0.5601]
 [-2.3702 -1.8608 -2.3702 -1.8608]
 [-0.8608  0.5601 -0.8608  0.5601]]


In [35]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
print(arr[inds])

[700 100 200 600]


In [37]:
print(arr.take(inds))
arr.put(inds, 42)
print(arr)
arr.put(inds, [40, 41, 42, 43])
print(arr)

[40 41 42 43]
[  0  42  42 300 400 500  42  42 800 900]
[  0  41  42 300 400 500  43  40 800 900]


In [38]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
print(arr)
print(arr.take(inds, axis=1))

[[-1.2659  0.1198 -1.0635  0.3329]
 [-2.3594 -0.1995 -1.542  -0.9707]]
[[-1.0635 -1.2659 -1.0635  0.1198]
 [-1.542  -2.3594 -1.542  -0.1995]]


In [39]:
arr = np.arange(5)
print(arr)
print(arr*4)

[0 1 2 3 4]
[ 0  4  8 12 16]


In [42]:
arr = np.random.randn(4, 3)
print(arr)
print(arr.mean(0))
demeaned = arr - arr.mean(0)
print(demeaned)
print(demeaned.mean(0))

[[-0.6525 -1.2183 -1.3326]
 [ 1.0746  0.7236  0.69  ]
 [ 1.0015 -0.5031 -0.6223]
 [-0.9212 -0.7262  0.2229]]
[ 0.1256 -0.431  -0.2605]
[[-0.7781 -0.7873 -1.0721]
 [ 0.949   1.1546  0.9505]
 [ 0.8759 -0.0721 -0.3618]
 [-1.0468 -0.2952  0.4834]]
[ 0. -0. -0.]


In [43]:
print(arr)
row_means = arr.mean(1)
print(row_means.shape)
print(row_means.reshape((4, 1)))
demeaned = arr - row_means.reshape((4, 1))
print(demeaned.mean(1))

[[-0.6525 -1.2183 -1.3326]
 [ 1.0746  0.7236  0.69  ]
 [ 1.0015 -0.5031 -0.6223]
 [-0.9212 -0.7262  0.2229]]
(4,)
[[-1.0678]
 [ 0.8294]
 [-0.0413]
 [-0.4748]]
[ 0.  0.  0. -0.]


In [44]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [45]:
arr - arr.mean(1).reshape((4, 1))

array([[ 0.4153, -0.1505, -0.2648],
       [ 0.2452, -0.1058, -0.1394],
       [ 1.0428, -0.4618, -0.581 ],
       [-0.4463, -0.2514,  0.6977]])

In [46]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
print(arr_3d.shape)
arr_1d = np.random.normal(size=3)
print(arr_1d[:, np.newaxis])
print(arr_1d[np.newaxis, :])

(4, 1, 4)
[[ 0.0513]
 [-1.1577]
 [ 0.8167]]
[[ 0.0513 -1.1577  0.8167]]


In [48]:
arr = np.random.randn(3, 4 ,5)
print(arr)
depth_means = arr.mean(2)
print(depth_means)
print(depth_means.shape)
demeaned = arr - depth_means[:, :, np.newaxis]
print(demeaned.mean(2))

[[[-0.6534  0.187  -0.3917 -0.2723 -0.0171]
  [ 0.6803  0.6355 -0.7572  0.7181 -0.3043]
  [-1.6778  0.427  -1.5637 -0.3675  1.0459]
  [ 1.22   -0.2477 -0.4162 -0.1167 -1.8448]]

 [[ 2.0687 -0.777   1.4402 -0.1106  1.2274]
  [ 1.9208  0.7464  2.2247 -0.6794  0.7274]
  [-0.8687 -1.2139 -0.4706 -0.9192 -0.8388]
  [ 0.4352 -0.5578 -0.5675 -0.3726 -0.9266]]

 [[ 1.7551  1.2098  1.27   -0.9744 -0.6347]
  [-0.3957 -0.2894 -0.7343 -0.7285  0.8388]
  [ 0.2669  0.7212  0.911  -1.0209 -1.4134]
  [ 1.2966  0.2523  1.1275 -0.5684  0.3094]]]
[[-0.2295  0.1945 -0.4272 -0.2811]
 [ 0.7697  0.988  -0.8623 -0.3979]
 [ 0.5252 -0.2618 -0.107   0.4835]]
(3, 4)
[[ 0.  0.  0.  0.]
 [ 0.  0. -0.  0.]
 [-0. -0.  0.  0.]]


In [49]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)

    # This generalizes things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

In [51]:
arr = np.zeros((4,3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [52]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
print(arr)
arr[:2] = [[-1.37], [0.509]]
print(arr)

[[ 1.28  1.28  1.28]
 [-0.42 -0.42 -0.42]
 [ 0.44  0.44  0.44]
 [ 1.6   1.6   1.6 ]]
[[-1.37  -1.37  -1.37 ]
 [ 0.509  0.509  0.509]
 [ 0.44   0.44   0.44 ]
 [ 1.6    1.6    1.6  ]]
