In [7]:
from __future__ import division, print_function, unicode_literals
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10,6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

In [2]:
np.ones((10, 5)).shape

(10, 5)

In [3]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [8]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
print(np.issubdtype(ints.dtype, np.integer))
print(np.issubdtype(floats.dtype, np.floating))

True
True


In [9]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [11]:
np.uint32.mro()

[numpy.uint32,
 numpy.unsignedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [12]:
np.issubdtype(ints.dtype, np.number)

True

In [14]:
arr = np.arange(8)
print(arr)
arr.reshape((4,2))

[0 1 2 3 4 5 6 7]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [15]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
arr = np.arange(15)
arr.reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
other_arr = np.ones((3, 5))
print(other_arr.shape)
arr.reshape(other_arr.shape)

(3, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
arr = np.arange(15).reshape((5, 3))
print(arr)
arr.ravel()

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr = np.arange(12).reshape((3, 4))
print(arr)
print(arr.ravel())
print(arr.ravel('F'))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [22]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.concatenate([arr1, arr2], axis=0))
print(np.concatenate([arr1, arr2], axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [23]:
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [25]:
arr = np.random.randn(5, 2)
print(arr)
first, second, third = np.split(arr, [1, 3])
print(first)
print(second)
print(third)

[[ 1.0072 -1.2962]
 [ 0.275   0.2289]
 [ 1.3529  0.8864]
 [-2.0016 -0.3718]
 [ 1.669  -0.4386]]
[[ 1.0072 -1.2962]]
[[0.275  0.2289]
 [1.3529 0.8864]]
[[-2.0016 -0.3718]
 [ 1.669  -0.4386]]


In [27]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
print(np.r_[arr1, arr2])
print(np.c_[np.r_[arr1, arr2], arr])

[[ 0.      1.    ]
 [ 2.      3.    ]
 [ 4.      5.    ]
 [ 0.3026  0.5238]
 [ 0.0009  1.3438]
 [-0.7135 -0.8312]]
[[ 0.      1.      0.    ]
 [ 2.      3.      1.    ]
 [ 4.      5.      2.    ]
 [ 0.3026  0.5238  3.    ]
 [ 0.0009  1.3438  4.    ]
 [-0.7135 -0.8312  5.    ]]


In [28]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [29]:
arr = np.arange(3)
print(arr)
arr.repeat(3)

[0 1 2]


array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [30]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [31]:
arr = np.random.randn(2, 2)
print(arr)
arr.repeat(2, axis=0)

[[-2.3702 -1.8608]
 [-0.8608  0.5601]]


array([[-2.3702, -1.8608],
       [-2.3702, -1.8608],
       [-0.8608,  0.5601],
       [-0.8608,  0.5601]])

In [32]:
print(arr.repeat([2, 3], axis=0))
print(arr.repeat([2, 3], axis=1))

[[-2.3702 -1.8608]
 [-2.3702 -1.8608]
 [-0.8608  0.5601]
 [-0.8608  0.5601]
 [-0.8608  0.5601]]
[[-2.3702 -2.3702 -1.8608 -1.8608 -1.8608]
 [-0.8608 -0.8608  0.5601  0.5601  0.5601]]


In [33]:
print(arr)
np.tile(arr, 2)

[[-2.3702 -1.8608]
 [-0.8608  0.5601]]


array([[-2.3702, -1.8608, -2.3702, -1.8608],
       [-0.8608,  0.5601, -0.8608,  0.5601]])

In [34]:
print(arr)
print(np.tile(arr, (2, 1)))
print(np.tile(arr, (3, 2)))

[[-2.3702 -1.8608]
 [-0.8608  0.5601]]
[[-2.3702 -1.8608]
 [-0.8608  0.5601]
 [-2.3702 -1.8608]
 [-0.8608  0.5601]]
[[-2.3702 -1.8608 -2.3702 -1.8608]
 [-0.8608  0.5601 -0.8608  0.5601]
 [-2.3702 -1.8608 -2.3702 -1.8608]
 [-0.8608  0.5601 -0.8608  0.5601]
 [-2.3702 -1.8608 -2.3702 -1.8608]
 [-0.8608  0.5601 -0.8608  0.5601]]


In [35]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
print(arr[inds])

[700 100 200 600]


In [37]:
print(arr.take(inds))
arr.put(inds, 42)
print(arr)
arr.put(inds, [40, 41, 42, 43])
print(arr)

[40 41 42 43]
[  0  42  42 300 400 500  42  42 800 900]
[  0  41  42 300 400 500  43  40 800 900]


In [38]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
print(arr)
print(arr.take(inds, axis=1))

[[-1.2659  0.1198 -1.0635  0.3329]
 [-2.3594 -0.1995 -1.542  -0.9707]]
[[-1.0635 -1.2659 -1.0635  0.1198]
 [-1.542  -2.3594 -1.542  -0.1995]]


In [39]:
arr = np.arange(5)
print(arr)
print(arr*4)

[0 1 2 3 4]
[ 0  4  8 12 16]


In [42]:
arr = np.random.randn(4, 3)
print(arr)
print(arr.mean(0))
demeaned = arr - arr.mean(0)
print(demeaned)
print(demeaned.mean(0))

[[-0.6525 -1.2183 -1.3326]
 [ 1.0746  0.7236  0.69  ]
 [ 1.0015 -0.5031 -0.6223]
 [-0.9212 -0.7262  0.2229]]
[ 0.1256 -0.431  -0.2605]
[[-0.7781 -0.7873 -1.0721]
 [ 0.949   1.1546  0.9505]
 [ 0.8759 -0.0721 -0.3618]
 [-1.0468 -0.2952  0.4834]]
[ 0. -0. -0.]


In [43]:
print(arr)
row_means = arr.mean(1)
print(row_means.shape)
print(row_means.reshape((4, 1)))
demeaned = arr - row_means.reshape((4, 1))
print(demeaned.mean(1))

[[-0.6525 -1.2183 -1.3326]
 [ 1.0746  0.7236  0.69  ]
 [ 1.0015 -0.5031 -0.6223]
 [-0.9212 -0.7262  0.2229]]
(4,)
[[-1.0678]
 [ 0.8294]
 [-0.0413]
 [-0.4748]]
[ 0.  0.  0. -0.]


In [44]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [45]:
arr - arr.mean(1).reshape((4, 1))

array([[ 0.4153, -0.1505, -0.2648],
       [ 0.2452, -0.1058, -0.1394],
       [ 1.0428, -0.4618, -0.581 ],
       [-0.4463, -0.2514,  0.6977]])

In [46]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
print(arr_3d.shape)
arr_1d = np.random.normal(size=3)
print(arr_1d[:, np.newaxis])
print(arr_1d[np.newaxis, :])

(4, 1, 4)
[[ 0.0513]
 [-1.1577]
 [ 0.8167]]
[[ 0.0513 -1.1577  0.8167]]


In [48]:
arr = np.random.randn(3, 4 ,5)
print(arr)
depth_means = arr.mean(2)
print(depth_means)
print(depth_means.shape)
demeaned = arr - depth_means[:, :, np.newaxis]
print(demeaned.mean(2))

[[[-0.6534  0.187  -0.3917 -0.2723 -0.0171]
  [ 0.6803  0.6355 -0.7572  0.7181 -0.3043]
  [-1.6778  0.427  -1.5637 -0.3675  1.0459]
  [ 1.22   -0.2477 -0.4162 -0.1167 -1.8448]]

 [[ 2.0687 -0.777   1.4402 -0.1106  1.2274]
  [ 1.9208  0.7464  2.2247 -0.6794  0.7274]
  [-0.8687 -1.2139 -0.4706 -0.9192 -0.8388]
  [ 0.4352 -0.5578 -0.5675 -0.3726 -0.9266]]

 [[ 1.7551  1.2098  1.27   -0.9744 -0.6347]
  [-0.3957 -0.2894 -0.7343 -0.7285  0.8388]
  [ 0.2669  0.7212  0.911  -1.0209 -1.4134]
  [ 1.2966  0.2523  1.1275 -0.5684  0.3094]]]
[[-0.2295  0.1945 -0.4272 -0.2811]
 [ 0.7697  0.988  -0.8623 -0.3979]
 [ 0.5252 -0.2618 -0.107   0.4835]]
(3, 4)
[[ 0.  0.  0.  0.]
 [ 0.  0. -0.  0.]
 [-0. -0.  0.  0.]]


In [49]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)

    # This generalizes things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

In [51]:
arr = np.zeros((4,3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [52]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
print(arr)
arr[:2] = [[-1.37], [0.509]]
print(arr)

[[ 1.28  1.28  1.28]
 [-0.42 -0.42 -0.42]
 [ 0.44  0.44  0.44]
 [ 1.6   1.6   1.6 ]]
[[-1.37  -1.37  -1.37 ]
 [ 0.509  0.509  0.509]
 [ 0.44   0.44   0.44 ]
 [ 1.6    1.6    1.6  ]]


In [53]:
arr = np.arange(10)
print(np.add.reduce(arr))
arr.sum()

45


45

In [55]:
np.random.seed(123456)
arr = np.random.randn(5, 5)
print(arr[::2].sort(1))
print(arr[:, :-1] < arr[:, 1:])
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

None
[[ True  True  True  True]
 [ True False  True False]
 [ True  True  True  True]
 [False  True False False]
 [ True  True  True  True]]


array([ True, False,  True, False,  True])

In [56]:
arr = np.arange(15).reshape((3,5))
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [57]:
arr = np.arange(3).repeat([1, 2, 2])
print(arr)
np.multiply.outer(arr, np.arange(5))

[0 1 1 2 2]


array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [59]:
x, y = np.random.randn(3, 4), np.random.randn(5)
result = np.subtract.outer(x, y)
result.shape

(3, 4, 5)

In [60]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17], dtype=int32)

In [61]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
print(arr)
np.add.reduceat(arr, [0, 2, 4], axis=1)

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]]


array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]], dtype=int32)

In [62]:
def add_elements(x, y):
    return x+y

add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [63]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [64]:
arr = np.random.randn(10000)
%timeit add_them(arr, arr)
%timeit np.add(arr, arr)

100 loops, best of 3: 2.48 ms per loop
The slowest run took 13.85 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.74 µs per loop


In [66]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

array([(1.5   ,  6), (3.1416, -2)], dtype=[('x', '<f8'), ('y', '<i4')])

In [67]:
print(sarr[0])
print(sarr[0]['y'])

(1.5, 6)
6


In [68]:
sarr['x']

array([1.5   , 3.1416])

In [71]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [72]:
arr[0]['x']

array([0, 0, 0], dtype=int64)

In [73]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [70]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
print(data['x'])
print(data['y'])
print(data['x']['a'])

[(1., 2.) (3., 4.)]
[5 6]
[1. 3.]


In [75]:
arr = np.random.randn(6)
arr.sort()
print(arr)

[-3.0561 -0.0186  0.1113  0.3122  0.6473  0.7002]


In [76]:
arr = np.random.rand(3, 5)
print(arr)
arr[:, 0].sort()
print(arr)

[[0.2584 0.6594 0.639  0.868  0.6504]
 [0.142  0.8594 0.9413 0.3289 0.3967]
 [0.8535 0.0583 0.8634 0.7673 0.4716]]
[[0.142  0.6594 0.639  0.868  0.6504]
 [0.2584 0.8594 0.9413 0.3289 0.3967]
 [0.8535 0.0583 0.8634 0.7673 0.4716]]


In [77]:
arr = np.random.randn(5)
print(arr)
np.sort(arr)
print(arr)

[ 2.0136 -0.428  -0.6845 -0.9441  0.8845]
[ 2.0136 -0.428  -0.6845 -0.9441  0.8845]


In [78]:
arr = np.random.randn(3, 5)
print(arr)
arr.sort(axis=1)
print(arr)

[[-0.0497  0.3306  0.3909  0.251   0.7214]
 [ 0.5335  0.1051 -0.1094 -0.6001 -0.8971]
 [ 0.0355  1.7821  0.6751 -0.4457  0.8641]]
[[-0.0497  0.251   0.3306  0.3909  0.7214]
 [-0.8971 -0.6001 -0.1094  0.1051  0.5335]
 [-0.4457  0.0355  0.6751  0.8641  1.7821]]


In [80]:
arr[:, ::-1]

array([[ 0.7214,  0.3909,  0.3306,  0.251 , -0.0497],
       [ 0.5335,  0.1051, -0.1094, -0.6001, -0.8971],
       [ 1.7821,  0.8641,  0.6751,  0.0355, -0.4457]])

In [81]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
print(indexer)
print(values[indexer])

[1 2 4 3 0]
[0 1 2 3 5]


In [84]:
arr = np.random.randn(3, 5)
arr[0] = values
print(arr)
print(arr[:, arr[0].argsort()])

[[ 5.      0.      1.      3.      2.    ]
 [-0.5861  1.0293 -0.6128 -0.5175  0.1599]
 [ 1.     -1.6473 -0.0667 -2.0574 -0.8782]]
[[ 0.      1.      2.      3.      5.    ]
 [ 1.0293 -0.6128  0.1599 -0.5175 -0.5861]
 [-1.6473 -0.0667 -0.8782 -2.0574  1.    ]]


In [86]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
print(sorter)
print(zip(last_name[sorter], first_name[sorter]))

[1 2 3 0 4]


In [87]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind="mergesort")
print(indexer)
values.take(indexer)

[2 3 4 0 1]


array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

In [91]:
np.random.seed(12345)
arr = np.random.randn(20)
print(arr)
print(np.partition(arr, 3))

[-0.2047  0.4789 -0.5194 -0.5557  1.9658  1.3934  0.0929  0.2817  0.769
  1.2464  1.0072 -1.2962  0.275   0.2289  1.3529  0.8864 -2.0016 -0.3718
  1.669  -0.4386]
[-2.0016 -1.2962 -0.5557 -0.5194 -0.3718 -0.4386 -0.2047  0.2817  0.769
  0.4789  1.0072  0.0929  0.275   0.2289  1.3529  0.8864  1.3934  1.9658
  1.669   1.2464]


In [92]:
indices = np.argpartition(arr, 3)
print(indices)
arr.take(indices)

[16 11  3  2 17 19  0  7  8  1 10  6 12 13 14 15  5  4 18  9]


array([-2.0016, -1.2962, -0.5557, -0.5194, -0.3718, -0.4386, -0.2047,
        0.2817,  0.769 ,  0.4789,  1.0072,  0.0929,  0.275 ,  0.2289,
        1.3529,  0.8864,  1.3934,  1.9658,  1.669 ,  1.2464])

In [94]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

3

In [95]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5], dtype=int64)

In [96]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])
arr.searchsorted([0, 1], side="right")

array([3, 7], dtype=int64)

In [97]:
data = np.floor(np.random.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

array([9940., 6768., 7908., 1709.,  268., 8003., 9037.,  246., 4917.,
       5262., 5963.,  519., 8950., 7282., 8183., 5002., 8101.,  959.,
       2189., 2587., 4681., 4593., 7095., 1780., 5314., 1677., 7688.,
       9281., 6094., 1501., 4896., 3773., 8486., 9110., 3838., 3154.,
       5683., 1878., 1258., 6875., 7996., 5735., 9732., 6340., 8884.,
       4954., 3516., 7142., 5039., 2256.])

In [98]:
labels = bins.searchsorted(data)
labels

array([4, 4, 4, 3, 2, 4, 4, 2, 3, 4, 4, 2, 4, 4, 4, 4, 4, 2, 3, 3, 3, 3,
       4, 3, 4, 3, 4, 4, 4, 3, 3, 3, 4, 4, 3, 3, 4, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 4, 4, 3], dtype=int64)

In [99]:
pd.Series(data).groupby(labels).mean()

2     498.000000
3    3064.277778
4    7389.035714
dtype: float64

In [100]:
import numpy as np

def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

In [101]:
x = np.random.randn(10000000)

In [102]:
y = np.random.randn(10000000)

In [103]:
%timeit mean_distance(x, y)

1 loop, best of 3: 5.46 s per loop


In [104]:
%timeit (x-y).mean()

10 loops, best of 3: 56.9 ms per loop


In [105]:
import numba as nb

In [106]:
numba_mean_distance = nb.jit(mean_distance)

In [107]:
%timeit numba_mean_distance(x, y)

The slowest run took 1042.12 times longer than the fastest. This could mean that an intermediate result is being cached.
1 loop, best of 3: 13.9 ms per loop


In [108]:
from numba import float64, njit

In [109]:
@njit(float64(float64[:], float64[:]))
def mean_distance(x, y):
    return (x - y).mean()

In [110]:
%timeit mean_distance(x, y)

10 loops, best of 3: 60.3 ms per loop


In [111]:
from numba import vectorize

In [115]:
@vectorize
def nb_add(x, y):
    return x + y

x = np.arange(10)
nb_add(x, x)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int64)

In [116]:
nb_add.accumulate(x, 0)

ValueError: could not find a matching type for nb_add.accumulate, requested type has type code 'l'

In [120]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10000, 10000))
mmap

OSError: [Errno 22] Invalid argument: 'mymmap'

In [118]:
section = mmap[:5]

In [119]:
section[:] = np.random.randn(5, 10000)
mmap.flush()
mmap
del mmap

In [121]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

memmap([[ 1.3714,  0.9313,  0.6057, ..., -0.6212, -0.4678,  0.4787],
        [ 0.423 ,  0.8306,  0.6998, ...,  1.2883,  0.5886, -1.4276],
        [ 2.1601, -1.2462,  2.4447, ...,  0.8687,  0.2802,  2.1301],
        ...,
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ]])

In [122]:
%xdel mmap
!rm mymmap

'rm' is not recognized as an internal or external command,
operable program or batch file.


In [124]:
arr_c = np.ones((1000, 1000), order='C')
arr_f = np.ones((1000, 1000), order='F')
print('C Flags')
print(arr_c.flags)
print('F Flags')
print(arr_f.flags)
print('F Flags contiguous')
print(arr_f.flags.f_contiguous)

C Flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
F Flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
F Flags contiguous
True


In [125]:
%timeit arr_c.sum(1)
%timeit arr_f.sum(1)

1000 loops, best of 3: 1.28 ms per loop
1000 loops, best of 3: 744 µs per loop


In [126]:
arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [128]:
print(arr_c[:50].flags.contiguous)
arr_c[:, :50].flags

True


  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [129]:
%xdel arr_c
%xdel arr_f

In [130]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS